### ISSUE TITLE
Integration in company erp

### ISSUE THREAD

**Issue by namannj46** [BookStackApp/api-scripts#10]
We have successfully implemented the login with Google option. However, we are currently facing a challenge in enabling login for our organization's employees. We need assistance in finding a solution that allows users with the same domain name, such as "[...@xyz.com](mailto:...@xyz.com)," to log in. Can you please help us with this?
Currently i am able to login with google with my own id only

**Comment by ssddanbrown** [comment]
There's not really enough detail for me to understand the issue here.
- Are those employees part of a your orgs google workspace?
  - If not, do you have a central authentication system for employees? If so, what is it?
- Have you tried using the email domain restriction option in registration settings?
- What happens then you attempt to log without a different account?
- What does this have to do with a company ERP, or this api-scripts repository?

**Comment by namannj46** [comment]
Are those employees part of a your orgs google workspace? --> Yes

Have you tried using the email domain restriction option in registration settings? -->yes but it is not authenticating the emails, no email verification mails are sent.

What does this have to do with a company ERP, or this api-scripts repository?--> Actually we want to associate this with our company, so i raise this issue here

**Comment by ssddanbrown** [comment]
> no email verification mails are sent.

Are emails working on your instance in general? There's a test email button in the settings.
You should make sure you've set valid SMTP server settings that work for your domain, and have changed the mail from name/address.
