### ISSUE TITLE
Big Images  at convert

### ISSUE THREAD

**Issue by pbordon** [BookStackApp/api-scripts#3]
In a conversion from word with cuted images, the images are converted in original size, and not in docx size.
I Attached a demo 

![Ejemplo_node_docx_to_html](https://user-images.githubusercontent.com/77298966/127330078-b65abd9e-aada-4ceb-8540-69fca0ca3136.png)

**Comment by ssddanbrown** [comment]
Hi @pbordon,
The Docx to HTML conversion library used focuses output cleanliness and reliability rather than achieving best visual replication. docx to HTML, with an output that would be appropriate for BookStack, is not an simple thing and there's likely to be many other issues and concerns with a conversion like that.

Since the scripts in this repo are primarily examples of API usage I don't really want to spend time on any edge-case minor issues in the usage of these scripts so will therefore close this off.
