### ISSUE TITLE
php-generate-sitemap - no chapters

### ISSUE THREAD

**Issue by Badiboy** [BookStackApp/api-scripts#4]
Thank you for the very useful script.

Could you please check, why php-generate-sitemap does not generate links for chapters? Like this:
https://demo.bookstackapp.com/books/dummy-content-book/chapter/chapter-a

_(If you need a ready test case - I can provide you the private API access)._

**Comment by ssddanbrown** [comment]
Hi @Badiboy,

I think this was generating such chapter links but they would not be output due to an error in how I was joining together all the different endpoints. Have addressed this in f165f615fae3b415cbf47a96661c4d43043e6a11 so, with those changes, you should now get chapter endpoints also. Have verified this on my local dev instance.

**Comment by Badiboy** [comment]
Thank you, it seems fine now!
